config:
  info: springcloud-cofig-test,versin=2
server:
  port: 3366
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka.didispace.com/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
