config:
  info: springcloud-cofig-dev,versin=1
server:
  port: 3355
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka.didispace.com/eureka/